apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - image: busybox
      name: busybox
      ports:
        - containerPort: 80
      command: ['sh', '-c', 'while true; do echo New random number is $(( ( RANDOM % 100 )  + 1 )); sleep 2; done']