apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - image: nginx:1.12
          name: nginx
          env:
            - name: USERNAME
              value: "Oleg"
          ports:
            - containerPort: 80
          command: ['sh', '-c', 'while true; do echo "Hello, ${USERNAME}!"; sleep 2; done']
